import time
import os


def main(input_filename: str):
    # Generated by generate_files.py on Wed Nov 17 2021

    # Return value of -1 is used to signal that this isn't implemented.
    # Once it is, remove/replace that return (implicitly returning None is fine).
    return -1


if __name__ == "__main__":
    def run_main():
        os.chdir(os.path.split(__file__)[0])
        main("../../inputs/2016/day17.txt")

    run_main()
