# Generated by generate_files.py on Sun Nov 14 2021

def run_day(year: int, day: int):
    filename = f"../inputs/{year}/day{day:02d}.txt"    if year == 2015:
        if day == 1:
            import year2015.day01
            return year2015.day01.main(filename)
        elif day == 2:
            import year2015.day02
            return year2015.day02.main(filename)
        elif day == 3:
            import year2015.day03
            return year2015.day03.main(filename)
        elif day == 4:
            import year2015.day04
            return year2015.day04.main(filename)
        elif day == 5:
            import year2015.day05
            return year2015.day05.main(filename)
        elif day == 6:
            import year2015.day06
            return year2015.day06.main(filename)
        elif day == 7:
            import year2015.day07
            return year2015.day07.main(filename)
        elif day == 8:
            import year2015.day08
            return year2015.day08.main(filename)
        elif day == 9:
            import year2015.day09
            return year2015.day09.main(filename)
        elif day == 10:
            import year2015.day10
            return year2015.day10.main(filename)
        elif day == 11:
            import year2015.day11
            return year2015.day11.main(filename)
        elif day == 12:
            import year2015.day12
            return year2015.day12.main(filename)
        elif day == 13:
            import year2015.day13
            return year2015.day13.main(filename)
        elif day == 14:
            import year2015.day14
            return year2015.day14.main(filename)
        elif day == 15:
            import year2015.day15
            return year2015.day15.main(filename)
        elif day == 16:
            import year2015.day16
            return year2015.day16.main(filename)
        elif day == 17:
            import year2015.day17
            return year2015.day17.main(filename)
        elif day == 18:
            import year2015.day18
            return year2015.day18.main(filename)
        elif day == 19:
            import year2015.day19
            return year2015.day19.main(filename)
        elif day == 20:
            import year2015.day20
            return year2015.day20.main(filename)
        elif day == 21:
            import year2015.day21
            return year2015.day21.main(filename)
        elif day == 22:
            import year2015.day22
            return year2015.day22.main(filename)
        elif day == 23:
            import year2015.day23
            return year2015.day23.main(filename)
        elif day == 24:
            import year2015.day24
            return year2015.day24.main(filename)
        elif day == 25:
            import year2015.day25
            return year2015.day25.main(filename)

    elif year == 2016:
        if day == 1:
            import year2016.day01
            return year2016.day01.main(filename)
        elif day == 2:
            import year2016.day02
            return year2016.day02.main(filename)
        elif day == 3:
            import year2016.day03
            return year2016.day03.main(filename)
        elif day == 4:
            import year2016.day04
            return year2016.day04.main(filename)
        elif day == 5:
            import year2016.day05
            return year2016.day05.main(filename)
        elif day == 6:
            import year2016.day06
            return year2016.day06.main(filename)
        elif day == 7:
            import year2016.day07
            return year2016.day07.main(filename)
        elif day == 8:
            import year2016.day08
            return year2016.day08.main(filename)
        elif day == 9:
            import year2016.day09
            return year2016.day09.main(filename)
        elif day == 10:
            import year2016.day10
            return year2016.day10.main(filename)
        elif day == 11:
            import year2016.day11
            return year2016.day11.main(filename)
        elif day == 12:
            import year2016.day12
            return year2016.day12.main(filename)
        elif day == 13:
            import year2016.day13
            return year2016.day13.main(filename)
        elif day == 14:
            import year2016.day14
            return year2016.day14.main(filename)
        elif day == 15:
            import year2016.day15
            return year2016.day15.main(filename)
        elif day == 16:
            import year2016.day16
            return year2016.day16.main(filename)
        elif day == 17:
            import year2016.day17
            return year2016.day17.main(filename)
        elif day == 18:
            import year2016.day18
            return year2016.day18.main(filename)
        elif day == 19:
            import year2016.day19
            return year2016.day19.main(filename)
        elif day == 20:
            import year2016.day20
            return year2016.day20.main(filename)
        elif day == 21:
            import year2016.day21
            return year2016.day21.main(filename)
        elif day == 22:
            import year2016.day22
            return year2016.day22.main(filename)
        elif day == 23:
            import year2016.day23
            return year2016.day23.main(filename)
        elif day == 24:
            import year2016.day24
            return year2016.day24.main(filename)
        elif day == 25:
            import year2016.day25
            return year2016.day25.main(filename)

    elif year == 2017:
        if day == 1:
            import year2017.day01
            return year2017.day01.main(filename)
        elif day == 2:
            import year2017.day02
            return year2017.day02.main(filename)
        elif day == 3:
            import year2017.day03
            return year2017.day03.main(filename)
        elif day == 4:
            import year2017.day04
            return year2017.day04.main(filename)
        elif day == 5:
            import year2017.day05
            return year2017.day05.main(filename)
        elif day == 6:
            import year2017.day06
            return year2017.day06.main(filename)
        elif day == 7:
            import year2017.day07
            return year2017.day07.main(filename)
        elif day == 8:
            import year2017.day08
            return year2017.day08.main(filename)
        elif day == 9:
            import year2017.day09
            return year2017.day09.main(filename)
        elif day == 10:
            import year2017.day10
            return year2017.day10.main(filename)
        elif day == 11:
            import year2017.day11
            return year2017.day11.main(filename)
        elif day == 12:
            import year2017.day12
            return year2017.day12.main(filename)
        elif day == 13:
            import year2017.day13
            return year2017.day13.main(filename)
        elif day == 14:
            import year2017.day14
            return year2017.day14.main(filename)
        elif day == 15:
            import year2017.day15
            return year2017.day15.main(filename)
        elif day == 16:
            import year2017.day16
            return year2017.day16.main(filename)
        elif day == 17:
            import year2017.day17
            return year2017.day17.main(filename)
        elif day == 18:
            import year2017.day18
            return year2017.day18.main(filename)
        elif day == 19:
            import year2017.day19
            return year2017.day19.main(filename)
        elif day == 20:
            import year2017.day20
            return year2017.day20.main(filename)
        elif day == 21:
            import year2017.day21
            return year2017.day21.main(filename)
        elif day == 22:
            import year2017.day22
            return year2017.day22.main(filename)
        elif day == 23:
            import year2017.day23
            return year2017.day23.main(filename)
        elif day == 24:
            import year2017.day24
            return year2017.day24.main(filename)
        elif day == 25:
            import year2017.day25
            return year2017.day25.main(filename)

    elif year == 2018:
        if day == 1:
            import year2018.day01
            return year2018.day01.main(filename)
        elif day == 2:
            import year2018.day02
            return year2018.day02.main(filename)
        elif day == 3:
            import year2018.day03
            return year2018.day03.main(filename)
        elif day == 4:
            import year2018.day04
            return year2018.day04.main(filename)
        elif day == 5:
            import year2018.day05
            return year2018.day05.main(filename)
        elif day == 6:
            import year2018.day06
            return year2018.day06.main(filename)
        elif day == 7:
            import year2018.day07
            return year2018.day07.main(filename)
        elif day == 8:
            import year2018.day08
            return year2018.day08.main(filename)
        elif day == 9:
            import year2018.day09
            return year2018.day09.main(filename)
        elif day == 10:
            import year2018.day10
            return year2018.day10.main(filename)
        elif day == 11:
            import year2018.day11
            return year2018.day11.main(filename)
        elif day == 12:
            import year2018.day12
            return year2018.day12.main(filename)
        elif day == 13:
            import year2018.day13
            return year2018.day13.main(filename)
        elif day == 14:
            import year2018.day14
            return year2018.day14.main(filename)
        elif day == 15:
            import year2018.day15
            return year2018.day15.main(filename)
        elif day == 16:
            import year2018.day16
            return year2018.day16.main(filename)
        elif day == 17:
            import year2018.day17
            return year2018.day17.main(filename)
        elif day == 18:
            import year2018.day18
            return year2018.day18.main(filename)
        elif day == 19:
            import year2018.day19
            return year2018.day19.main(filename)
        elif day == 20:
            import year2018.day20
            return year2018.day20.main(filename)
        elif day == 21:
            import year2018.day21
            return year2018.day21.main(filename)
        elif day == 22:
            import year2018.day22
            return year2018.day22.main(filename)
        elif day == 23:
            import year2018.day23
            return year2018.day23.main(filename)
        elif day == 24:
            import year2018.day24
            return year2018.day24.main(filename)
        elif day == 25:
            import year2018.day25
            return year2018.day25.main(filename)

    elif year == 2019:
        if day == 1:
            import year2019.day01
            return year2019.day01.main(filename)
        elif day == 2:
            import year2019.day02
            return year2019.day02.main(filename)
        elif day == 3:
            import year2019.day03
            return year2019.day03.main(filename)
        elif day == 4:
            import year2019.day04
            return year2019.day04.main(filename)
        elif day == 5:
            import year2019.day05
            return year2019.day05.main(filename)
        elif day == 6:
            import year2019.day06
            return year2019.day06.main(filename)
        elif day == 7:
            import year2019.day07
            return year2019.day07.main(filename)
        elif day == 8:
            import year2019.day08
            return year2019.day08.main(filename)
        elif day == 9:
            import year2019.day09
            return year2019.day09.main(filename)
        elif day == 10:
            import year2019.day10
            return year2019.day10.main(filename)
        elif day == 11:
            import year2019.day11
            return year2019.day11.main(filename)
        elif day == 12:
            import year2019.day12
            return year2019.day12.main(filename)
        elif day == 13:
            import year2019.day13
            return year2019.day13.main(filename)
        elif day == 14:
            import year2019.day14
            return year2019.day14.main(filename)
        elif day == 15:
            import year2019.day15
            return year2019.day15.main(filename)
        elif day == 16:
            import year2019.day16
            return year2019.day16.main(filename)
        elif day == 17:
            import year2019.day17
            return year2019.day17.main(filename)
        elif day == 18:
            import year2019.day18
            return year2019.day18.main(filename)
        elif day == 19:
            import year2019.day19
            return year2019.day19.main(filename)
        elif day == 20:
            import year2019.day20
            return year2019.day20.main(filename)
        elif day == 21:
            import year2019.day21
            return year2019.day21.main(filename)
        elif day == 22:
            import year2019.day22
            return year2019.day22.main(filename)
        elif day == 23:
            import year2019.day23
            return year2019.day23.main(filename)
        elif day == 24:
            import year2019.day24
            return year2019.day24.main(filename)
        elif day == 25:
            import year2019.day25
            return year2019.day25.main(filename)

    elif year == 2020:
        if day == 1:
            import year2020.day01
            return year2020.day01.main(filename)
        elif day == 2:
            import year2020.day02
            return year2020.day02.main(filename)
        elif day == 3:
            import year2020.day03
            return year2020.day03.main(filename)
        elif day == 4:
            import year2020.day04
            return year2020.day04.main(filename)
        elif day == 5:
            import year2020.day05
            return year2020.day05.main(filename)
        elif day == 6:
            import year2020.day06
            return year2020.day06.main(filename)
        elif day == 7:
            import year2020.day07
            return year2020.day07.main(filename)
        elif day == 8:
            import year2020.day08
            return year2020.day08.main(filename)
        elif day == 9:
            import year2020.day09
            return year2020.day09.main(filename)
        elif day == 10:
            import year2020.day10
            return year2020.day10.main(filename)
        elif day == 11:
            import year2020.day11
            return year2020.day11.main(filename)
        elif day == 12:
            import year2020.day12
            return year2020.day12.main(filename)
        elif day == 13:
            import year2020.day13
            return year2020.day13.main(filename)
        elif day == 14:
            import year2020.day14
            return year2020.day14.main(filename)
        elif day == 15:
            import year2020.day15
            return year2020.day15.main(filename)
        elif day == 16:
            import year2020.day16
            return year2020.day16.main(filename)
        elif day == 17:
            import year2020.day17
            return year2020.day17.main(filename)
        elif day == 18:
            import year2020.day18
            return year2020.day18.main(filename)
        elif day == 19:
            import year2020.day19
            return year2020.day19.main(filename)
        elif day == 20:
            import year2020.day20
            return year2020.day20.main(filename)
        elif day == 21:
            import year2020.day21
            return year2020.day21.main(filename)
        elif day == 22:
            import year2020.day22
            return year2020.day22.main(filename)
        elif day == 23:
            import year2020.day23
            return year2020.day23.main(filename)
        elif day == 24:
            import year2020.day24
            return year2020.day24.main(filename)
        elif day == 25:
            import year2020.day25
            return year2020.day25.main(filename)


if __name__ == "__main__":
    print("This module is intended to be imported.")
